### ISSUE TITLE
Add fsanitize testing

### ISSUE THREAD

**Issue by aprokop** [arborx/ArborX#64]
Found some issues in #63. Plus we would want to satisfy an optional requirement of xSDK (cf #58).

**Comment by aprokop** [comment]
Actually, `fsanitize` is probably preferred to `valgrind`.

**Comment by masterleinad** [comment]
I just have problems running `CMake` using `MPI` then.

**Comment by dalg24** [comment]
You probably need a suppression file.  Bruno had added one in DTK.  Refer to ORNL-CEES/DataTransferKit@d2c8c4f

**Comment by masterleinad** [comment]
With `-fsanitize=leak` and surpressing errors for `libopenpal.so`(no `CUDA`), I currently see:
```
 SUMMARY: LeakSanitizer: 33065 byte(s) leaked in 407 allocation(s).
13:     #1 0x7fab0e05a547  (<unknown module>)
13:
13: Indirect leak of 80 byte(s) in 1 object(s) allocated from:
13:     #0 0x7fab12d80acb in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/liblsan.so.0+0xeacb)
13:     #1 0x7fab0a158edc  (<unknown module>)
13:
13: Indirect leak of 56 byte(s) in 1 object(s) allocated from:
13:     #0 0x7fab12d80acb in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/liblsan.so.0+0xeacb)
13:     #1 0x7f0dd9e75484  (<unknown module>)
13:     #2 0x3433  (<unknown module>)
13:
13: Indirect leak of 48 byte(s) in 2 object(s) allocated from:
13:     #0 0x7f0ddec05acb in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/liblsan.so.0+0xeacb)
13:     #1 0x7f0431fa9c4c  (<unknown module>)
13:
```

**Comment by aprokop** [comment]
Apparently we are not doing it, it's been 3 years.

**Comment by dalg24** [comment]
Sure.  We can always re-open as necessary.  I have a suppression file laying around somewhere for stuff from Boost.  I typically didn't use with MPI (mostly because I usually don't enable to save time when developing these days)
